version: "3"

networks:
  dirtybitsnetwork:
    name: dirtybitsnetwork
    driver: bridge

services:
  mailweb:
    build: .
    container_name: mailweb
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    environment:
      - DB_HOST=mail_db
      - DB_NAME=mail
      - DB_USER=server
      - DB_PASSWORD=server
    networks:
      - dirtybitsnetwork
    depends_on:
      - mail_db
  mail_db:
    image: postgres
    container_name: mail_db
    environment:
      - POSTGRES_DB=mail
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server
    ports:
      - "5435:5432"
    networks:
      - dirtybitsnetwork
